### ISSUE TITLE
Progress display shows two % signs instead of one

### ISSUE THREAD

**Issue by elkayem** [OctoPrint/OctoPrint-DisplayProgress#1]
This is a really minor one... I am running OctoPrint 1.2 8 master branch on a RasPi 2, and Marlin 1.1.0 RC3 with a 12864 full graphic LCD on a Prusa i3 using ArduinoMega 2560 and RAMPS 1.4.  It is a fresh install as of today using OctoPi, so I haven't had many opportunities to mess things up, but it wouldn't be the first time.  

DisplayProgress is a super nice feature, but the display isn't quite right.  On the screen, there are two '%' signs rather than one.  See below.  

![img_0944](https://cloud.githubusercontent.com/assets/14856215/12044296/ca311962-ae43-11e5-9880-5fac20bcaaae.JPG)

Also (and unrelated) not sure if this other anomaly is a real feature or not...  When the print stops, the timer on the LCD continues to count up until the next print.  I probably need to do a little hunting on my end first for this feature.

**Comment by elkayem** [comment]
Also, not sure if this helps, but here is an example M117 command from the terminal window:
Send: N70941 M117 [######### ]  93%%*0

**Comment by lukie80** [comment]
I'm not familiar with the plugin system. If you find the plugin file on your system (my /home/pi/.octoprint/plugins folder is empty) just remove one of the two %% characters from the code.

[edit] I'm not an attentive man. Open your "config.yaml" file and look for the config part which is shown [at the bottom of this page](https://github.com/OctoPrint/OctoPrint-DisplayProgress).
