### ISSUE TITLE
Up for adoption

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint-DisplayProgress#10]
I have my hands way too full with OctoPrint's maintenance to give this plugin the attention it needs. Hence I'm looking for a new maintainer to adopt it.

**Comment by jneilliii** [comment]
Gina, I'll take this one on if no-one else has. Fits in my wheelhouse of M117 plugins.

**Comment by foosel** [comment]
@jneilliii sure! I'll give you admin access right away!

**Comment by foosel** [comment]
Should be done. Feel free to remove the note in the `README` and close this ticket :)

**Comment by jneilliii** [comment]
Thanks Gina. Glad to help.
