### ISSUE TITLE
Progress on the CR10 screen doesn't match the one in Octoprint

### ISSUE THREAD

**Issue by Ozkovacs** [OctoPrint/OctoPrint-DisplayProgress#13]
Hi there.
I really like the idea of seeing the progress in the CR10 screen - makes a lot more sense than having to go to my computer (not in the same room) to see the progress.
However, using the latest OcotPrint (OctoPrint 1.7.3 Python 3.7.3 OctoPi 0.18.0 at the time of this), I see the following:
OctoPrint : 46%
DisplayProgress : 30%

Thanks!

**Comment by Ozkovacs** [comment]
My print is getting further, and the DisplayProgress seems to slowly catch up with OctoPrint.
It's now:
OctoPrint :61%
DisplayProgress : 57%

So maybe DisplayProgress is displaying "only" the print, and OctoPrint also displays some other stuff like heating up, probe, ...

**Comment by jneilliii** [comment]
Do you have the Print Time Genius plugin installed by chance?

**Comment by Ozkovacs** [comment]
Hi Jneilliii.
Yes, you are right - I do have Print Time Genius....that might be what's creating the confusion.
Thanks for your fast reply!  Makes sense now!
