### ISSUE TITLE
Reset Stat after print end job

### ISSUE THREAD

**Issue by Adefx** [OctoPrint/OctoPrint-DisplayProgress#4]
Anyway to display another message after the prints ends ? 
Display & octoprint keep displaying [########] 100%
Thx
Edit :
The trick is to include a m117 Message at the end Gcode.
Thanks for your work ;)

**Comment by foosel** [comment]
Your edit is actually what I was going to suggest, utilizing the built-in GCODE script feature or adding an M117 to your slicer's end GCODE script.

So, happy now and this can be closed?

**Comment by foosel** [comment]
\o/ :tada:
