### ISSUE TITLE
Initial progress message

### ISSUE THREAD

**Issue by sanchosk** [OctoPrint/OctoPrint-DisplayProgress#5]
There is one slight flaw - if the print file is quite big (~30MB or so) it takes quite a while until the first 1% message is displayed.
The plugin should send 0% progress bar at the initial start of the print.

**Comment by foosel** [comment]
Should be solved by 901b9b5224c3270419a3bd2375e4496d026acd49 which I just pushed with version 0.1.2. Thanks for the heads-up, I actually managed to never notice this issue!
