### ISSUE TITLE
which printers?

### ISSUE THREAD

**Issue by ManuelW77** [OctoPrint/OctoPrint-DisplayProgress#7]
hey there,

on which printers does it work?

**Comment by foosel** [comment]
Printers that display stuff sent to them via [M117](http://reprap.org/wiki/G-code#M117:_Display_Message) on their display. Most of them (with a display) do, some don't, I don't have a list, sorry. If `M117 Hello` sent via the Terminal tab in OctoPrint doesn't display "Hello" on your printer's display, this plugin won't work either.
