### ISSUE TITLE
Doesn't display progress. Only once the print finishes.

### ISSUE THREAD

**Issue by xXRoboBoyXx** [OctoPrint/OctoPrint-DisplayProgress#9]
When it's printing a file, It just shows "Printing..." And not "[##               ] %12" Or whatever it normally shows. When it finishes, It shows "[##########] 100%"
Is it because the plugin isn't compatible with Marlin on the Anet A8? Or am i just using it wrong?

**Comment by foosel** [comment]
Please provide `octoprint.log` and a `serial.log`.

**Comment by xXRoboBoyXx** [comment]
[octoprint.log](https://github.com/OctoPrint/OctoPrint-DisplayProgress/files/1860850/octoprint.log)
[serial.log](https://github.com/OctoPrint/OctoPrint-DisplayProgress/files/1860851/serial.log)

**Comment by foosel** [comment]
Your `serial.log` wasn't enabled :) Please enable it, reproduce the issue, then upload the log.

**Comment by xXRoboBoyXx** [comment]
New serial.log
[serial.log](https://github.com/OctoPrint/OctoPrint-DisplayProgress/files/1860979/serial.log)

**Comment by quintesse** [comment]
I have the same problem and looking at @xXRoboBoyXx 's log I only see 2 M117 messages being sent: one for 0% and one for 100%.

**Comment by quintesse** [comment]
I'm  guessing that for some reason the `on_print_progress()` never gets called in our case.

**Comment by foosel** [comment]
I still haven't been able to reproduce this. I use the plugin myself and it works flawlessly on my prints.

How are you printing (through USB or from the printer's SD)? What other plugins do you have installed?

**Comment by quintesse** [comment]
I'm printing directly from OctoPrint (using OctoPi) over USB. And the DisplayProgress plugin is the only (non-default) one I have installed. My printer is a Prusa MK3, not sure if that is in any way important.

**Comment by foosel** [comment]
I also have a MK3 with which things work fine, so I don't think that's the reason here. Odd.

**Comment by quintesse** [comment]
Ok. Btw I'm a programmer myself so just tell me if you need me to test anything.

**Comment by foosel** [comment]
Sadly I don't have any ideas at the moment. `on_print_progress` gets called centrally within OctoPrint. Based on the behaviour it must either not be called in your case, or it gets called but for whatever reason the check if the printer is printing fails. Both would be a bug in OctoPrint proper. 

If you can reliably reproduce it, what could help is adding some logging statements in `on_print_progress` to check if it's actually called. Even better would be debug-stepping through it.

I sadly have my hands way too full for the foreseeable future to be able to do that myself, plus I can't reproduce it at all. So if you or anyone else with a development background who is able to reproduce could take a closer look at that, that would certainly be appreciated.

**Comment by quintesse** [comment]
I just restarted my rPi and with the current print the progress works fine so that doesn't help trying to debug things ;)

I was thinking what you said about the check whether the printer is actually printing. IIRC when the progress didn't work the display showed "heating...". Also the start end end messages don't check for the printer status so that would explain why the 100% appears correctly. So my guess is the print check doesn't work in certain situations. 

When my current print is done I'll try some scenarios to reproduce the problem.

**Comment by quintesse** [comment]
I just had a mid-print error (using old filament, it broke) from which the MK3 recuperated gracefully, but after that there was no progress reporting anymore. This might be an additional indication that after an error the internal state of the communication object is incorrect.

**Comment by quintesse** [comment]
Oops, sorry, I said "additional indication" but I had actually not written before about my suspicion that the problem might be with an error state that doesn't get cleared. Because one thing I remembered is that when I first installed the plugin I had reset the printer some hours before. OctoPrint showed a message that a reset had been detected and kept working seemingly without any problems.

**Comment by quintesse** [comment]
Latest update: once you have the issue disconnecting and reconnecting fixes it.

**Comment by foosel** [comment]
That definitely sounds like some state isn't properly mapped. You mentioned a mid-print error - what was reported from the firmware?

What confuses me is that OctoPrint wouldn't continue pushing the print job to the printer if it didn't think it was printing. So something about this whole scenario is still odd.

**Comment by quintesse** [comment]
> what was reported from the firmware?

I didn't check at the moment, sorry.

> So something about this whole scenario is still odd.

Let me see if I can force this issue by for example resetting the printer (while connected but not printing) and then printing something. Hopefully that's enough to reproduce this and then I could put in some debug statements to see what the printer's state is.

**Comment by quintesse** [comment]
> Hopefully that's enough to reproduce this

Unfortunately it isn't that easy :/
It probably has to be a "real" error or something.
